# test google response
x = {'general': {'search_engine': 'google', 'results_cnt': 16200000, 'search_time': 0.55, 'language': 'en',
                 'mobile': False, 'basic_view': False, 'search_type': 'text',
                 'page_title': 'Ari E Craig The George Washington University contact info - Google Search',
                 'timestamp': '2023-11-19T16:27:48.115Z'}, 'input': {
    'original_url': 'https://www.google.com/search?q=Ari%20E%20Craig%20The%20George%20Washington%20University%20contact%20info&brd_json=1',
    'request_id': 'hl_23bd325f_m45d1pd0yd'}, 'organic': [{'link': 'https://www.linkedin.com/in/ari-craig-a84523144',
                                                          'display_link': 'https://www.linkedin.com › ari-craig-a84523144',
                                                          'title': 'Ari Craig - Naval Officer - US Navy',
                                                          'description': 'Outstanding Naval Officer and trusted legal advisor whose exceptional professional military record demonstrates his distinctive ability to, not only, ...',
                                                          'extensions': [{'type': 'text',
                                                                          'text': 'Norfolk, Virginia, United States',
                                                                          'rank': 1},
                                                                         {'type': 'text', 'text': 'Naval Officer',
                                                                          'rank': 2},
                                                                         {'type': 'text', 'text': 'US Navy',
                                                                          'rank': 3}], 'rank': 1, 'global_rank': 1},
                                                         # {'link': 'https://my.gwu.edu/mod/directory/?dept_id=2067',
                                                         #  'display_link': 'https://my.gwu.edu › mod › directory',
                                                         #  'title': 'Directories - myGW - The George Washington University',
                                                         #  'description': 'Craig E Geist. (202) 741-2800. Send Craig an e-mail. Professor Emeritus of ... Terms of Service | Site Help | Contact Us. © 2023, The George Washington ...',
                                                         #  'extensions': [{'type': 'missing', 'text': 'Ari', 'rank': 1},
                                                         #                 {'type': 'must_include', 'text': 'Ari',
                                                         #                  'link': 'https://www.google.com/search?sca_esv=583796676&gl=us&hl=en&q=%22Ari%22+E+Craig+The+George+Washington+University+contact+info&sa=X&ved=2ahUKEwjK0YbMvdCCAxUYxQIHHVevC-YQ5t4CegQIFBAB',
                                                         #                  'rank': 2}], 'rank': 2, 'global_rank': 2},
                                                         {'link': 'https://bulletin.gwu.edu/faculty/',
                                                          'display_link': 'https://bulletin.gwu.edu › faculty',
                                                          'title': 'Faculty',
                                                          'description': 'Ed.D., George Washington University. Toni E. Marsh, Associate Professor in the College of Professional Studies B.A. 1987, J.D. 1990, Cleveland State ...',
                                                          'rank': 3, 'global_rank': 3}, {
                                                             'link': 'https://www.law.gwu.edu/environmental-energy-law-faculty',
                                                             'display_link': 'https://www.law.gwu.edu › environmental-energy-law...',
                                                             'title': 'Environmental & Energy Law Faculty - GW Law',
                                                             'description': 'Environmental & Energy Law Faculty. Co-directors: Randall Abate, Assistant Dean for Environmental Law. Donna Attanasio, Assistant Dean for Energy Law ...',
                                                             'rank': 4, 'global_rank': 4}, {
                                                             'link': 'https://business.commencement.gwu.edu/sites/g/files/zaxdzs4571/files/2023-05/sb_23_commencement_graduate_nocrop_remediated.pdf',
                                                             'display_link': 'https://business.commencement.gwu.edu › files',
                                                             'title': '2023 - GW School of Business Commencement',
                                                             'description': 'May 19, 2023 — I offer congratulations to The Class of 2023 of the George Washington University. School of Business. Whether you earned a graduate degree or ...',
                                                             'extensions': [{'inline': True, 'type': 'text',
                                                                             'text': 'May 19, 2023', 'rank': 1},
                                                                            {'inline': True, 'type': 'text',
                                                                             'text': 'I offer congratulations to The Class of 2023 of the George Washington University. School of Business. Whether you earned a graduate degree or ...',
                                                                             'rank': 2}], 'rank': 5, 'global_rank': 5},
                                                         {
                                                             'link': 'https://www.alumni.gwu.edu/us-regional-alumni-networks',
                                                             'display_link': 'https://www.alumni.gwu.edu › us-regional-alumni-net...',
                                                             'title': 'U.S. Regional Alumni Networks - GW Alumni Association',
                                                             'description': 'U.S. Regional Alumni Networks are volunteer-led networks that connect GW alumni to fellow alumni in their regions.',
                                                             'rank': 6, 'global_rank': 6},
                                                         {'link': 'https://careerservices.gwu.edu/our-team',
                                                          'display_link': 'https://careerservices.gwu.edu › our-team',
                                                          'title': 'Our Team | Center for Career Services',
                                                          'description': 'The staff of the George Washington University Center for Career Services ... - Career Coach: US Politics & Government - craig.crutchfield@gwu.edu · Cole Gaudin ...',
                                                          'extensions': [{'type': 'missing', 'text': 'Ari', 'rank': 1},
                                                                         {'type': 'missing', 'text': 'E', 'rank': 2}],
                                                          'rank': 7, 'global_rank': 7}, {
                                                             'link': 'https://www.zoominfo.com/p/Craig-Crutchfield/935959392',
                                                             'display_link': 'https://www.zoominfo.com › Craig-Crutchfield',
                                                             'title': 'Craig Crutchfield Email & Phone Number - George..',
                                                             'description': 'Career Coach at George Washington University. Craig Crutchfield is a Career Coach at George Washington University based in Washington, District of Columbia.',
                                                             'rank': 8, 'global_rank': 8},
                                                         {'link': 'https://www.coursicle.com/gwu/professors/',
                                                          'display_link': 'https://www.coursicle.com › gwu › professors',
                                                          'title': 'Professors at The George Washington University',
                                                          'description': 'All professors at The George Washington University (GW) in Washington, D.C..',
                                                          'rank': 9, 'global_rank': 9}, {
                                                             'link': 'https://www.fastpeoplesearch.com/ariel-craig_id_G1000967608995613477',
                                                             'display_link': 'https://www.fastpeoplesearch.com › ariel-craig_id_G100...',
                                                             'title': 'Ariel Craig in Washington, DC (District of Columbia)',
                                                             'description': "Ariel Craig's current address is 4258 E Capitol St NE, Unit 104, Washington DC 20019. Ariel has lived there for about 3 years, since December of 2019. Who ...",
                                                             'rank': 10, 'global_rank': 10}],
     'pagination': {'current_page': 1,
                    'next_page_link': 'https://www.google.com/search?q=Ari+E+Craig+The+George+Washington+University+contact+info&sca_esv=583796676&gl=us&hl=en&ei=gjdaZcqIGZiKi-gP196usA4&start=10&sa=N',
                    'next_page_start': 10, 'next_page': 2}}

