bright_data:
  SERP_SSL: r"C:\Users\1\Downloads\ca.crt"
  HTTP: 'http://brd-customer-hl_23bd325f-zone-serp:834ucdyvfehn@brd.superproxy.io:22225'
  HTTPS: 'http://brd-customer-hl_23bd325f-zone-serp:834ucdyvfehn@brd.superproxy.io:22225'
