serp:
  url: 'https://www.google.com/search?'
  http_proxy: 'http://brd-customer-hl_b0a9f9cc-zone-serp_api1:1h0ms6dnwge5@brd.superproxy.io:22225'
  https_proxy: 'http://brd-customer-hl_b0a9f9cc-zone-serp_api1:1h0ms6dnwge5@brd.superproxy.io:22225'
