serp:
  url: 'https://www.google.com/search?'
  http_proxy: 'http://brd-customer-hl_ce63cbe3-zone-serp:m2e1h1yartv7@brd.superproxy.io:22225'
  https_proxy: 'http://brd-customer-hl_ce63cbe3-zone-serp:m2e1h1yartv7@brd.superproxy.io:22225'
